name: Publish

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: |
          yarn install
          npm version --no-commit-hooks --no-git-tag-version ${{ github.ref_name }}
          npm publish --access public

      - name: Get latest release info
        id: get-release-info
        uses: release-flow/keep-a-changelog-action/get-release-info@v1
        with:
          release-version: latest

      - name: Publish to Github releases
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.get-release-info.outputs.release-notes }}
          # prerelease: true
          # files: '*.vsix'